### ISSUE TITLE
About CUDA is out of the memory.

### ISSUE THREAD

**Issue by huizhang2017** [ZhangLingMing1/TSGCNet#2]
HI, ZhangLingMing ,
       I am very interesting in your paper about TSGCNet and try to run it with the data you supplied. I copied the data several times with different file names. And now the training dataset is extended to 8 copies. When I run train.py and  just run the TSGCNet.py, with your default settings, both failed and report that:
       " RuntimeError: CUDA out of memory ......" 
       My GPU is 1080Ti  ( 11GB ) , the memory is larger than the GPU you used in your paper. So it is very strange why the memory is not enough? I also tried to set the batch_size =1, failed too. 
 
Thanks for disclosing your codes.

**Comment by cl1218** [comment]
HI,I also encountered the same problem. How did you solve it.

**Comment by mikkelmedm** [comment]
I have similar issue. @ZhangLingMing1 hoping for a solution

**Comment by ZhangLingMing1** [comment]
You can try to reduce the number of feature channels to save memory. In our expermental, we put some pre-computing processes on the CPU, but it's very time-consuming.
