### ISSUE TITLE
Is there a typo?   "coor3, nor3, index = get_graph_feature(nor2, coor2, k=self.k)"

### ISSUE THREAD

**Issue by huizhang2017** [ZhangLingMing1/TSGCNet#3]
hi, ZhangLingMing,
      I think there is a typo in TSGCNet.py : 
      
       "coor3, nor3, index = get_graph_feature(nor2, coor2, k=self.k)"

 Please check. By the way, if we correct this bug, will the result be better?

**Comment by ZhangLingMing1** [comment]
hi, Zhanghui
Thank you for pointing out this problem, we will correct this bug. This problem should be that I modified the algorithm before debugging, but forgot to modify it back. But thank you again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangLingMing1/TSGCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月21日(星期二) 下午3:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZhangLingMing1/TSGCNet] Is there a typo?   "coor3, nor3, index = get_graph_feature(nor2, coor2, k=self.k)" (Issue #3)





 
hi, ZhangLingMing,
 I think there is a typo in TSGCNet.py :
    "coor3, nor3, index = get_graph_feature(nor2, coor2, k=self.k)"  
Please check. By the way, if we correct this bug, will the result be better?
