### ISSUE TITLE
How to calculate the normal vector for each vertice?

### ISSUE THREAD

**Issue by huizhang2017** [ZhangLingMing1/TSGCNet#4]
Hi, ZhangLingMing,
      I tried to calculate the normal vector for each vertice by sum all the normal vectors of the meshes contain this vertice, i also consider the weight (calculated by mesh area or angle of this vertice in the mesh) of each mesh contain this vertices, but found there are big difference between my calculation and the value in your data sample. However, the normal vector for each mesh is same as my calculation.       

      So I was wondering how to calculate the normal vector of each vertice in your paper? Thanks .

**Comment by ZhangLingMing1** [comment]
Hi!
We get the normal vectors from the meshlab (software)， which can exoprt the normal vectors when save each dental model.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangLingMing1/TSGCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 中午11:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZhangLingMing1/TSGCNet] How to calculate the normal vector for each vertice? (Issue #4)





 
Hi, ZhangLingMing,
 I tried to calculate the normal vector for each vertice by sum all the normal vectors of the meshes contain this vertice, i also consider the weight (calculated by mesh area or angle of this vertice in the mesh) of each mesh contain this vertices, but found there are big difference between my calculation and the value in your data sample. However, the normal vector for each mesh is same as my calculation.

**Comment by huizhang2017** [comment]
OK, I see. Thanks.
