### ISSUE TITLE
Hello author, do you downsample the data before entering the network?

### ISSUE THREAD

**Issue by 2667402485chen** [ZhangLingMing1/TSGCNet#8]
Hello ZhangLingMing:
Did you downsample the point cloud data before feeding it into the network? Is it downsampling to a uniform number of points? I changed my data to the sample data format you provided and downsampled it before feeding it into the network, but the number of points obtained by downsampling each data is not the same.
 I don't know if this is the reason why my code keeps getting stuck report an error. Do you have any suggestion? I'm just starting to get in touch with this, so please enlighten me if I have any shortcomings. Looking forward to your reply.
![1661850840973](https://user-images.githubusercontent.com/76081479/187398623-64e96ca3-ec51-4cbc-91c9-769024f71620.png)

**Comment by thomhert** [comment]
Hi @ZhangLingMing1 
I also experienced the same problem of different dimension of dataset. Could be useful if you can share how to downsample the data.
Also, I tried batch_size = 2 and batch_size= 1, both worked well. But I got errors if I set batch_size with other numbers.
Thank you!

**Comment by ZhangLingMing1** [comment]
we use meshlab (a software) to down sample the point to 16000 before feeding it into the network
